apiVersion: v1
kind: Pod
metadata:
  name: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:8.0
    resources:
      limits:
        cpu: "0.25"
        memory: "2Mi"
      requests:
        cpu: "0.25"
        memory: "1Mi"
    ports:
    - containerPort: 7500
    imagePullPolicy: Always
