apiVersion: v1
kind: Pod
metadata:
   name: Tomcat
spec:
   containers:
   - name: tomcat
      image: tomcat
      resources:
      limits:
        cpu: "0.5"
        memory: "8Mi"
      requests:
        cpu: "0.25"
        memory: "8Mi"
      ports:
containerPort: 7500
   imagePullPolicy: Always
