apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "1Mi"
      requests:
        cpu: "0.25"
        memory: "1Mi"
    ports:
    - containerPort: 80
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
