apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "1Mi"
      requests:
        cpu: "0.25"
        memory: "1Mi"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    resources:
      limits:
        cpu: "0.5"
        memory: "1Mi"
      requests:
        cpu: "0.25"
        memory: "1Mi"
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://kubernetes.io
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
